import esbuild from 'esbuild';

import process from 'process';

import { copyFileSync, cpSync, mkdirSync, readFileSync } from 'fs';

import builtins from 'builtin-modules';



const pdfWorkerCode = readFileSync(

  'node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs',

  'utf8'

);



function copyPdfAssets() {

  mkdirSync('pdf-assets', { recursive: true });

  for (const dir of ['wasm', 'standard_fonts', 'iccs']) {

    cpSync(`node_modules/pdfjs-dist/${dir}`, `pdf-assets/${dir}`, {

      recursive: true,

    });

  }

}



function copyFoliateAssets() {

  cpSync('node_modules/foliate-js', 'foliate', { recursive: true });

  cpSync('src/assets/foliate/epub-bridge.html', 'foliate/epub-bridge.html');

  cpSync('src/assets/foliate/epub-bridge.js', 'foliate/epub-bridge.js');

}

function copyPdfJsViewerAssets() {
  for (const dir of [
    'web',
    'build',
    'cmaps',
    'standard_fonts',
    'wasm',
    'iccs',
    'image_decoders',
  ]) {
    cpSync(`node_modules/pdfjs-dist/${dir}`, `pdfjs/${dir}`, {
      recursive: true,
    });
  }
  cpSync('src/assets/pdfjs/pandocit-viewer.html', 'pdfjs/web/pandocit-viewer.html');
  cpSync('src/assets/pdfjs/pandocit-viewer.js', 'pdfjs/web/pandocit-viewer.js');
}



const banner = `/*

THIS IS A GENERATED/BUNDLED FILE BY ESBUILD

if you want to view the source, please visit the github repository of this plugin

*/

`;



const prod = process.argv[2] === 'production';



esbuild

  .build({

    banner: {

      js: banner,

    },

    entryPoints: ['./src/main.ts'],

    bundle: true,

    external: [

      'obsidian',

      'electron',

      '@codemirror/autocomplete',

      '@codemirror/closebrackets',

      '@codemirror/collab',

      '@codemirror/commands',

      '@codemirror/comment',

      '@codemirror/fold',

      '@codemirror/gutter',

      '@codemirror/highlight',

      '@codemirror/history',

      '@codemirror/language',

      '@codemirror/lint',

      '@codemirror/matchbrackets',

      '@codemirror/panel',

      '@codemirror/rangeset',

      '@codemirror/rectangular-selection',

      '@codemirror/search',

      '@codemirror/state',

      '@codemirror/stream-parser',

      '@codemirror/text',

      '@codemirror/tooltip',

      '@codemirror/view',

      'node:*',

      ...builtins,

    ],

    format: 'cjs',

    watch: !prod,

    target: 'es2020',

    logLevel: 'info',

    sourcemap: prod ? false : 'inline',

    treeShaking: true,

    outfile: 'main.js',

    minify: prod,

    define: {

      __PDF_WORKER_CODE__: JSON.stringify(pdfWorkerCode),

    },

  })

  .then(() => {

    copyFileSync(

      'node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs',

      'pdf.worker.min.mjs'

    );

    copyPdfAssets();

    copyFoliateAssets();

    copyPdfJsViewerAssets();

  })

  .catch(() => process.exit(1));

